version: "3"
services:
  sitespeed-firefox:
    image: ${DOCKER_REGISTRY}sitespeedio/sitespeed.io
    command: "--config ./config/config-firefox.json --preScript ./scripts/preScript.js http://demo:8080/demo/performance.html"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${http_proxy}
      - HTTPS_PROXY=${https_proxy}
      - NO_PROXY=${no_proxy}
    shm_size: 2g
    volumes:
      - ./performance/config:/sitespeed.io/config/
      - ./performance/scripts:/sitespeed.io/scripts/
      - ./performance/results/firefox/:/sitespeed.io/firefox-results/
  demo:
    image: ${DOCKER_REGISTRY}milieuinfo/node:12
    container_name: demo
    hostname: demo
    working_dir: /home/node/app
    entrypoint: bash -c "npm install && npm run demo"
    volumes:
      - .:/home/node/app

